require:
- rubocop-rails

AllCops:
  Exclude:
  - bin/**/*
  NewCops: enable

Layout/EndOfLine:
  Enabled: false

Documentation:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock: 
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true 

Lint/ToEnumArguments: 
  Enabled: true 

Lint/UnmodifiedReduceAccumulator: 
  Enabled: true 

Style/ArgumentsForwarding: 
  Enabled: true 

Style/CollectionCompact: 
  Enabled: true 

Style/DocumentDynamicEvalDefinition: 
  Enabled: true 

Style/NegatedIfElseCondition: 
  Enabled: true 

Style/SwapValues: 
  Enabled: true 

Rails/ActiveRecordCallbacksOrder: 
  Enabled: true 

Rails/AfterCommitOverride: 
  Enabled: true
